---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-disk-pvc
#  namespace: opc
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: sample-disk
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-counter-pvc
#  namespace: opc
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: sample-counter
  resources:
    requests:
      storage: 4Gi
