apiVersion: v1
kind: Service
metadata:
  name: opc-server
  labels:
    app: opc-server
spec:
   ports:
     - name: opc-server
       port: 8773
   type: LoadBalancer
   selector:
    app: opc-server

